### ISSUE TITLE
no parallel backend registered

### ISSUE THREAD

**Issue by xin0107** [yuabrahamliu/CWGCNA#2]

**Comment by yuabrahamliu** [comment]
What do you mean by that, please?

**Comment by xin0107** [comment]
I'm sorry about this. When running CWGCNA with my own data, I encountered an error. I intended to search for this problem using a search engine (paste and hit enter), but accidentally did so in the “Issues” page. I’m not sure yet whether it's an error with my own data or with the software. I'll figure it out and consult with you once I have clarity. My apologies.

**Comment by xin0107** [comment]
​Thank you for your concern. Now I can't solve the problem I'm having.
When I run the WGCNA with my own transcriptome data, I get two errors: 
1. `Error in { : task 1 failed - "replacement has 1 row, data has 19"`
2. `executing %dopar% sequentially: no parallel backend registered`
It seems to be a problem with parallel tasks and the second error reported by the “blockwiseModules” function. However, I don't encounter these errors when using the software's example data, and I also dont encounter them when running WGCNA with my own data. So, I'm not sure how these errors are being triggered. Can you explain it? Thanks a lot!

Here's the running code:
```
## Here's my own transcriptome data:
> head(pds,8)
       sampleid condition group
1      HT_AH_01        AH    AH
2      HT_AH_05        AH    AH
3      HT_AH_06        AH    AH
4    HT_CH4w_01      CH4w  CH4w
5    HT_CH4w_02      CH4w  CH4w
6    HT_CH4w_03      CH4w  CH4w
7  HT_CH4wNM_01    CH4wNM    NM
8  HT_CH4wNM_02    CH4wNM    NM

> dim(pds)
[1] 19  3

...

> top10k$betas[1:6,1:5]
                                                       HT_AH_01  HT_AH_05  HT_AH_06 HT_CH4w_01 HT_CH4w_02
ENSMUSG00000025902|Sox17      21.570772 12.469105 28.841912   13.44075  14.032233
ENSMUSG00000033845|Mrpl15    24.708546 21.141772 26.405899   20.86838  20.481704
ENSMUSG00000025903|Lypla1     28.902129 21.673114 24.639803   28.85285  37.347951
ENSMUSG00000033813|Tcea1      12.069422 11.064366  9.938543   12.91104  16.629982
ENSMUSG00000033793|Atp6v1h 16.145924 14.274195 20.420796   19.63599  22.367990
ENSMUSG00000025907|Rb1cc1    5.698804  5.813865  5.548463    6.05741   7.135798

> anovares <- featuresampling(betas = top10k$betas,
                            pddat = pds,
                            anova = TRUE,
                            plotannovares = TRUE,
                            featuretype = "gene",
                            plottitlesuffix = "hypoxia",
                            titlesize = 12,
                            textsize = 10,
                            threads = 30)
Error in { : task 1 failed - "replacement has 1 row, data has 19"

> cwgcnares <- diffwgcna(dat = betas,
                       pddat = pds,
                       responsevarname = "group",
                       confoundings = c("id"),
                       featuretype = "gene",
                       topvaricancetype = "sd",
                       topvaricance = 8000,
                       powers = seq(1, 25, 1),
                       rsqcutline = 0.7,
                       mediation = TRUE,
                       topn = 1,
                       plot = TRUE,
                       titleprefix = "Test",
                       labelnum = 5,
                       titlesize = 12,
                       textsize = 10,
                       annotextsize = 5,
                       pvalcolname = "adj.P.Val",
                       pvalcutoff = 0.05,
                       isbetaval = TRUE,
                       absxcutoff = 0,
                       diffcutoff = 0,
                       threads = 31)
The mediation analysis will be skipped because it only supports binary
        or continuous variables but the current response is not.
The ensemble mode only supports binary variable, but the current response is not.
Hence, the mode has been changed to normal mode.
pickSoftThreshold: will use block size 5592.
 pickSoftThreshold: calculating connectivity for given powers...
   ..working on genes 1 through 5592 of 8000
   ..working on genes 5593 through 8000 of 8000
   Power SFT.R.sq  slope truncated.R.sq mean.k. median.k. max.k.
1      1   0.6040  2.630          0.929 2930.00   3010.00 4200.0
2      2   0.1230  0.470          0.730 1490.00   1530.00 2700.0
3      3   0.0422 -0.230          0.631  880.00    881.00 1880.0
4      4   0.2440 -0.552          0.694  565.00    548.00 1380.0
5      5   0.3920 -0.718          0.770  384.00    359.00 1040.0
6      6   0.4950 -0.840          0.814  273.00    243.00  808.0
7      7   0.5590 -0.958          0.839  200.00    170.00  646.0
8      8   0.6120 -1.040          0.864  150.00    122.00  525.0
9      9   0.6600 -1.100          0.888  115.00     89.50  433.0
10    10   0.6870 -1.170          0.897   89.70     66.50  362.0
11    11   0.6950 -1.260          0.896   71.10     50.00  309.0
12    12   0.6850 -1.350          0.885   57.00     38.30  267.0
13    13   0.6730 -1.440          0.874   46.30     29.70  232.0
14    14   0.6610 -1.530          0.867   38.00     23.20  203.0
15    15   0.6660 -1.580          0.871   31.40     18.40  178.0
16    16   0.6840 -1.600          0.886   26.20     14.70  158.0
17    17   0.6830 -1.660          0.888   22.00     11.90  140.0
18    18   0.6750 -1.730          0.888   18.60      9.67  125.0
19    19   0.6560 -1.820          0.891   15.90      7.95  112.0
20    20   0.6680 -1.840          0.900   13.60      6.56  101.0
21    21   0.6800 -1.850          0.909   11.70      5.42   90.7
22    22   0.6910 -1.860          0.916   10.10      4.48   82.0
23    23   0.7030 -1.880          0.924    8.79      3.72   74.4
24    24   0.7120 -1.880          0.930    7.67      3.12   67.6
25    25   0.7210 -1.880          0.936    6.72      2.63   61.7
 Calculating module eigengenes block-wise from all genes
   Flagging genes and samples with too many missing values...
    ..step 1
 ....pre-clustering genes to determine blocks..
   Projective K-means:
   ..k-means clustering..
   ..merging smaller clusters...
Block sizes:
gBlocks
   1    2
4996 3004
 ..Working on block 1 .
    TOM calculation: adjacency..
    ..will use 31 parallel threads.
     Fraction of slow calculations: 0.000000
    ..connectivity..
    ..matrix multiplication (system BLAS)..
    ..normalization..
    ..done.
   ..saving TOM for block 1 into file blockwiseTOM.2024-05-13_11-18-53.393247-block.1.RData
 ....clustering..
 ....detecting modules..
 ....calculating module eigengenes..
 ....checking kME in modules..
 ..Working on block 2 .
    TOM calculation: adjacency..
    ..will use 31 parallel threads.
     Fraction of slow calculations: 0.000000
    ..connectivity..
    ..matrix multiplication (system BLAS)..
    ..normalization..
    ..done.
   ..saving TOM for block 2 into file blockwiseTOM.2024-05-13_11-18-53.393247-block.2.RData
 ....clustering..
 ....detecting modules..
 ....calculating module eigengenes..
 ....checking kME in modules..
 ..merging modules that are too close..
     mergeCloseModules: Merging modules whose distance is less than 0.2
       Calculating new MEs...
$mar
[1] 1 5 0 1

$mar
[1] 1 5 0 1

Warning message:
executing %dopar% sequentially: no parallel backend registered
```

**Comment by yuabrahamliu** [comment]
I can only see the head part of your `pds` data, and it seems your columns "condition" and "group" are the same, just with different names ("Ch4wNM" was changed to "NM"). If this is true for the whole `pds` data, please remove one of these repeated columns. 

In addition, for the parameter `confoundings` of the function `diffwgcna`, your setting was "id", which is not one of the column names of `pds`. Please change it to the one contained there (also remove any replicated columns in `pds` in advance), or change it to NULL if you don't have other confoundings.

Finally, your message states, "The mediation analysis will be skipped because it only supports binary or continuous variables, but the current response is not." Because your response variable "group" contains > 2 different values, which is not binary, the causal inference of `CWGCNA` cannot be performed. In this case, if you also don't have other confoundings, `diffwgcna` is the same as the normal `WGCNA`. If you want to use the causal inference, you need to change the "group" column to a binary one, such as keeping the "AH" group and merging all others to a "Non-AH" group—just a remainder.

**Comment by yuabrahamliu** [comment]
I have updated the package. You can reinstall it and have a try. Please begin from the settings `balanceadj` = FALSE and `threads` = 1 to see whether it works this time.

**Comment by xin0107** [comment]
In fact, as mentioned in your article, ‘The mediation analysis only supports binary or continuous variables,’ please forgive my carelessness. 
I have reinstalled `CWGCNA`, modified my group information, and also attempted to set `balanceadj = FALSE` and `threads=1`. However, some problems, including `no parallel backend registered`, still persist. 
Here's the running code:
```
> head(pds,8)
      sampleid group condition
1     HT_AH_01    AH       hyp
2     HT_AH_05    AH       hyp
3     HT_AH_06    AH       hyp
4   HT_CH4w_01  CH4w       hyp
5   HT_CH4w_02  CH4w       hyp
6   HT_CH4w_03  CH4w       hyp
7 HT_CH4wNM_01    NM      norm
8 HT_CH4wNM_02    NM      norm


> anovares <- featuresampling(betas = top10k$betas,
                            pddat = pds,
                            anova = TRUE,
                            plotannovares = TRUE,
                            featuretype = "gene",
                            plottitlesuffix = "Test",
                            titlesize = 12,
                            textsize = 10,
                            threads = 30) ##
Error in { : task 1 failed - "replacement has 1 row, data has 19"
> anovares <- featuresampling(betas = top10k$betas,
                            pddat = pds,
                            anova = TRUE,
                            plotannovares = TRUE,
                            featuretype = "gene",
                            plottitlesuffix = "Test",
                            titlesize = 12,
                            textsize = 10,
                            threads = 1) ##
Error in `$<-.data.frame`(`*tmp*`, "beta", value = list(HT_AH_01 = 21.570772,  :
  replacement has 1 row, data has 19


##  Settings balanceadj = FALSE and threads = 1
> cwgcnares <- diffwgcna(dat = betas,
                       pddat = pds,
                       responsevarname = "condition",
                       confoundings = c("group"),
                       featuretype = "gene",
                       topvaricancetype = "sd",
                       topvaricance = 8000,
                       balanceadj = FALSE, ##
                       powers = seq(1, 25, 1),
                       rsqcutline = 0.7,
                       mediation = TRUE,
                       topn = 1,
                       plot = TRUE,
                       titleprefix = "Test",
                       labelnum = 5,
                       titlesize = 12,
                       textsize = 10,
                       annotextsize = 5,
                       pvalcolname = "adj.P.Val",
                       pvalcutoff = 0.05,
                       isbetaval = TRUE,
                       absxcutoff = 0,
                       diffcutoff = 0,
                       threads = 1) ##
pickSoftThreshold: will use block size 5592.
 pickSoftThreshold: calculating connectivity for given powers...
   ..working on genes 1 through 5592 of 8000
   ..working on genes 5593 through 8000 of 8000
   Power SFT.R.sq  slope truncated.R.sq mean.k. median.k. max.k.
1      1   0.6040  2.630          0.929 2930.00   3010.00 4200.0
2      2   0.1230  0.470          0.730 1490.00   1530.00 2700.0
(...)
24    24   0.7120 -1.880          0.930    7.67      3.12   67.6
25    25   0.7210 -1.880          0.936    6.72      2.63   61.7
 Calculating module eigengenes block-wise from all genes
   Flagging genes and samples with too many missing values...
    ..step 1
 ....pre-clustering genes to determine blocks..
   Projective K-means:
   ..k-means clustering..
   ..merging smaller clusters...
Block sizes:
gBlocks
   1    2
4996 3004
 ..Working on block 1 .
    TOM calculation: adjacency..
    ..will not use multithreading.
     Fraction of slow calculations: 0.000000
    ..connectivity..
    ..matrix multiplication (system BLAS)..
    ..normalization..
    ..done.
   ..saving TOM for block 1 into file blockwiseTOM.2024-05-15_10-13-36.647342-block.1.RData
 ....clustering..
 ....detecting modules..
 ....calculating module eigengenes..
 ....checking kME in modules..
 ..Working on block 2 .
    TOM calculation: adjacency..
    ..will not use multithreading.
     Fraction of slow calculations: 0.000000
    ..connectivity..
    ..matrix multiplication (system BLAS)..
    ..normalization..
    ..done.
   ..saving TOM for block 2 into file blockwiseTOM.2024-05-15_10-13-36.647342-block.2.RData
 ....clustering..
 ....detecting modules..
 ....calculating module eigengenes..
 ....checking kME in modules..
 ..merging modules that are too close..
     mergeCloseModules: Merging modules whose distance is less than 0.2
       Calculating new MEs...
$mar
[1] 1 5 0 1

$mar
[1] 1 5 0 1

Start limma analysis on WGCNA modules
Coefficients not estimable: groupNM
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) :
  'x' must be atomic
In addition: Warning messages:
1: executing %dopar% sequentially: no parallel backend registered
2: Partial NA coefficients for 7 probe(s)
3: In .ebayes(fit = fit, proportion = proportion, stdev.coef.lim = stdev.coef.lim,  :
  Estimation of var.prior failed - set to default value
4: The `labeller` API has been updated. Labellers taking `variable` and `value` arguments are now deprecated.
ℹ See labellers documentation.

## Settings balanceadj = TRUE and threads = 31
> cwgcnares <- diffwgcna(dat = betas,
                       pddat = pds,
                       responsevarname = "condition",
                       confoundings = c("group"),
                       featuretype = "gene",
                       topvaricancetype = "sd",
                       topvaricance = 8000,
                       balanceadj = TRUE, ##
                       powers = seq(1, 25, 1),
                       rsqcutline = 0.7,
                       mediation = TRUE,
                       topn = 1,
                       plot = TRUE,
                       titleprefix = "Test",
                       labelnum = 5,
                       titlesize = 12,
                       textsize = 10,
                       annotextsize = 5,
                       pvalcolname = "adj.P.Val",
                       pvalcutoff = 0.05,
                       isbetaval = TRUE,
                       absxcutoff = 0,
                       diffcutoff = 0,
                       threads = 31) ##

pickSoftThreshold: will use block size 5592.
 pickSoftThreshold: calculating connectivity for given powers...
   ..working on genes 1 through 5592 of 8000
   ..working on genes 5593 through 8000 of 8000
   Power SFT.R.sq  slope truncated.R.sq mean.k. median.k. max.k.
1      1   0.6040  2.630          0.929 2930.00   3010.00 4200.0
2      2   0.1230  0.470          0.730 1490.00   1530.00 2700.0
(...)
24    24   0.7120 -1.880          0.930    7.67      3.12   67.6
25    25   0.7210 -1.880          0.936    6.72      2.63   61.7
 Calculating module eigengenes block-wise from all genes
   Flagging genes and samples with too many missing values...
    ..step 1
 ....pre-clustering genes to determine blocks..
   Projective K-means:
   ..k-means clustering..
   ..merging smaller clusters...
Block sizes:
gBlocks
   1    2
4996 3004
 ..Working on block 1 .
    TOM calculation: adjacency..
    ..will use 31 parallel threads.
     Fraction of slow calculations: 0.000000
    ..connectivity..
    ..matrix multiplication (system BLAS)..
    ..normalization..
    ..done.
   ..saving TOM for block 1 into file blockwiseTOM.2024-05-15_10-03-36.022086-block.1.RData
 ....clustering..
 ....detecting modules..
 ....calculating module eigengenes..
 ....checking kME in modules..
 ..Working on block 2 .
    TOM calculation: adjacency..
    ..will use 31 parallel threads.
     Fraction of slow calculations: 0.000000
    ..connectivity..
    ..matrix multiplication (system BLAS)..
    ..normalization..
    ..done.
   ..saving TOM for block 2 into file blockwiseTOM.2024-05-15_10-03-36.022086-block.2.RData
 ....clustering..
 ....detecting modules..
 ....calculating module eigengenes..
 ....checking kME in modules..
 ..merging modules that are too close..
     mergeCloseModules: Merging modules whose distance is less than 0.2
       Calculating new MEs...
$mar
[1] 1 5 0 1

$mar
[1] 1 5 0 1

Start limma analysis on WGCNA modules
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) :
  'x' must be atomic
In addition: There were 33 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In is.function(FUN) : closing unused connection 64 (<-localhost:11909)
2: In is.function(FUN) : closing unused connection 63 (<-localhost:11909)
(...)
31: In is.function(FUN) : closing unused connection 34 (<-localhost:11909)
32: executing %dopar% sequentially: no parallel backend registered
33: The `labeller` API has been updated. Labellers taking `variable` and `value` arguments are now deprecated.
ℹ See labellers documentation.
```

**Comment by yuabrahamliu** [comment]
Can you share a small dataset with the error? So that I can check from my side.

**Comment by xin0107** [comment]
Of course. 
[Test_CWGCNA_betas.csv](https://github.com/yuabrahamliu/CWGCNA/files/15317395/Test_CWGCNA_betas.csv)
[Test_CWGCNA_pds.csv](https://github.com/yuabrahamliu/CWGCNA/files/15317397/Test_CWGCNA_pds.csv)

**Comment by yuabrahamliu** [comment]
There are two problems. 

One of the issues is that you've transferred a data frame to the function `featuresampling`'s parameter `betas`, which should be a "Data matrix for feature selection, with features as rows and samples as columns", as indicated by the help document. I've made an update to the package so it will automatically convert it to a matrix, but please be aware that your data will be altered internally. However, this change should not affect the integrity of your data.

The other is that the variables "group" and "condition" have a singularity problem, and linear regression + ANOVA cannot be performed on them simultaneously. So, you need to remove one of them. If you would like more information, you can see this post. 

https://stackoverflow.com/questions/53989003/what-is-causing-this-error-coefficients-not-defined-because-of-singularities
